name: CI

on:
  push:
    branches: [ main ]
      
  pull_request:
    branches: [ main ]

jobs:
  build_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run dev
        run: |
         echo "Running dev"
      
  build_prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run prod
        run: |
         echo "Running prod"
      
  build_stg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run stg
        run: |
         echo "Running stg"
         
  deploy_dev:
    runs-on: ubuntu-latest
    needs: [build_dev]
    steps:
      - uses: actions/checkout@v2
      - name: Run stg
        run: |
         echo "Running stg"
