name: CI

on:
  push: 
#     tags:        
#       - /^release-dev-.*$/
  pull_request:
#   workflow_dispatch:

jobs:
  build_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run dev
        run: |
         echo "Running dev"
         
         
  deploy_dev:
    runs-on: ubuntu-latest
    needs: [build_dev]
    steps:
      - uses: actions/checkout@v2
      - name: Run deploy dev
        run: |
         echo "Running deploy dev"
         
  test_dev:
    runs-on: ubuntu-latest
    needs: [deploy_dev]
    steps:
      - uses: actions/checkout@v2
      - name: Run test dev
        run: |
         echo "Running test dev"
