name: Test rubocop and brakeman
on: 
  push: 
jobs:
  test_rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run rubocop
        run: bundle exec rubocop
      
  test_brakeman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run brakeman
        run: bundle exec brakeman --color
