name: Test rubocop and brakeman
on: 
  push: 
jobs:
  test_rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run rubocop
        run: |
         echo "run rubocop"
      
  test_brakeman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run brakeman
        run: echo "run brakeman"
