name: Test rubocop and brakeman
on: 
  push: 
jobs:
  test_rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
      - name: Run rubocop
        run: bundle exec rubocop
      
  test_brakeman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run brakeman
        run: bundle exec brakeman --color
